### ISSUE TITLE
`functional` class design

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3fda#1]
In a first step, let us only consider 1-D functional data. 
There are several layers of complexity we could consider

- ~`functional_matrix`: A functional is a `n x t` matrix. We assume that all values are made at the same `t` different time points.~
  Not supported by `data.table`
- `functional_list`: A `functional` feature is a list of  `n` `functions`:
    - variable length lists,
    - lists with a time component (e.g. a time-series) 
    - `Something from `tidyfun`
    
Proposal: Each of those has class `functional` and perhaps a more specific second class.

What do we need:
- [x] A converter to each sub-class
  - `as_functional_matrix`
  - `as_functional_list`
- [x] A converter to flatten (S3-method) to a matrix.
  - `flatten_functional` (S3) for the two sub-classes above)
- [x] `PipeOpFlatten`: Converts from `functional` to a `data.table` of `doubles`
- [x] `PipeOpExtractFeature`: Applies a function to each `functional`, e.g. m̀ean`.

Research:
- [x] What `functional_list` type do we want?

**Comment by sebffischer** [comment]
data.table does not support matrix columns
