### ISSUE TITLE
functional summary statistics

### ISSUE THREAD

**Issue by m-muecke** [mlr-org/mlr3fda#105]
The tf package now has functionwise https://tidyfun.github.io/tf/reference/functionwise.html statistics as well as general summary functions: https://tidyfun.github.io/tf/reference/tfsummaries.html check if it make sense to replace the custom pipe op extractor code

**Comment by m-muecke** [comment]
@sebffischer I think we should switch to `tf`s implementation, since they use the functional definitions which differs from our implementation or have them both and indicate that the one is the functional implementation, see the mean for example: https://tidyfun.github.io/tf/reference/functionwise.html:


``` r
library(mlr3fda)
library(mlr3pipelines)

# mlr3 implementation
task = tsk("fuel")
po_fmean = po("fda.extract", features = "mean") 
task_fmean = po_fmean$train(list(task))[[1L]]   
mlr_mean = task_fmean$data()$NIR_mean
head(mlr_mean)
#> [1] 0.49851677 0.42557851 0.01329275 0.02031529 0.08319121 0.11900065
```

``` r
# tf implementation
tf_mean = tf::tf_fmean(task$data()$NIR)
head(tf_mean)
#> [1] 0.49971996 0.42602058 0.01341115 0.02033672 0.08343140 0.11906268
```

``` r
# not the same
all.equal(mlr_mean, tf_mean)
#> [1] "Mean relative difference: 0.002684658"
```

<sup>Created on 2024-06-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by sebffischer** [comment]
But this will not work for our use case, where we ant to calculate the statistic on a subset, right?

**Comment by m-muecke** [comment]
> But this will not work for our use case, where we ant to calculate the statistic on a subset, right?

What do you mean by subset, the tf functions would work on a single column so the same what we currently do and allow for passing an `arg` argument for changing the domain:

``` r
library(mlr3fda)
#> Loading required package: mlr3
```

``` r
library(mlr3pipelines)

# mlr3 implementation
task = tsk("fuel")
po_min = po("fda.extract", features = "min")
task_fmin = po_min$train(list(task))[[1L]]
mlr_min = task_fmin$data()$NIR_min
head(mlr_min)
#> [1]  0.20950737  0.14228654 -0.09833023 -0.08504978 -0.22812462 -0.17281058
```

``` r
# tf implementation
tf_min = tf::tf_fmin(task$data()$NIR)
head(tf_min)
#> [1]  0.20950737  0.14228654 -0.09833023 -0.08504978 -0.22812462 -0.17281058
```

``` r
# not the same
all.equal(mlr_min, tf_min)
#> [1] TRUE
```

<sup>Created on 2024-06-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

What I've noticed is that our min/max and perhaps others are faster ~5ms compared to ~8ms

**Comment by sebffischer** [comment]
We have the `left` and `right` parameter: https://github.com/mlr-org/mlr3fda/blob/1bf8b2d206fd3bcdf0cf45796a082bdbd379d484/R/PipeOpFDAExtract.R#L66-L67

**Comment by sebffischer** [comment]
Of course there is some way to also do this with tf but our code runs, is not too slow and is well tested, so I would prioritize other things such as the book chapter and the correlation pipeop instead of a refactor

**Comment by m-muecke** [comment]
> Of course there is some way to also do this with tf but our code runs, is not too slow and is well tested, so I would prioritize other things such as the book chapter and the correlation pipeop instead of a refactor

I agree, but perhaps we should indicate in the docs that we're not using the functional mean, variance, etc. definitions and rather just an arithmetic mean for each grid point across all functions etc.
