### ISSUE TITLE
Functional Response

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3fda#12]
We should perhaps think about introducing a `TaskFunctionalRegr`. 
As an output, this task would have one of the `functional` feature classes we have designed. 

There is software that allows directly modeling functional responses, e.g. [FDBoost](https://rdrr.io/github/boost-R/FDboost/man/FDboost.html) and usig `keras`/`torch` its quite easy to model.

**Comment by sebffischer** [comment]
We will not work on this for now
