### ISSUE TITLE
PipeOp for correlation between feature’s 

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3fda#92]
tf_crossprod can be used fro the tf package

**Comment by fabian-s** [comment]
is implemented now:
```
#' @export
#' @describeIn functionwise cross-covariances between two functional vectors:
#'   \eqn{\tfrac{1}{|T|}\int_T (x_i(t) - \bar x(t)) (y_i(t)-\bar y(t)) dt}
tf_crosscov <- function(x, y, arg = tf_arg(x)) {
``

**Comment by fabian-s** [comment]
or rather:

```
 ' @describeIn functionwise cross-correlation between two functional vectors:
#'   `tf_crosscov(x, y) / (tf_fsd(x) * tf_fsd(y))`
tf_crosscor <- function(x, y, arg = tf_arg(x)) {
``

**Comment by sebffischer** [comment]
Blocked by: https://github.com/tidyfun/tf/pull/86/files

**Comment by m-muecke** [comment]
How should this behave? Should it act on two cols or on the entire data.table like `cor()` and return a correlation matrix? Then we would get for each observation/row a scalar correlation value. The only issue right now is that `tf_crosscor()` requires the same domain for x and y, i.e. we would have to transform it to the same domain first, I guess we would have to truncate it to the smallest domain then

**Comment by sebffischer** [comment]
> Should it act on two cols or on the entire data.table like cor() and return a correlation matrix?  

Yes, so I think each correlation-pair should become a column. But with `affect_columns` it is possible to operate on a subset.

> The only issue right now is that tf_crosscor() requires the same domain for x and y, i.e. we would have to transform it to the same domain first, I guess we would have to truncate it to the smallest domain.

Good point. The `tf_crosscor` has an argument `arg`, maybe we just let the user set this optionally?

**Comment by m-muecke** [comment]
> > Should it act on two cols or on the entire data.table like cor() and return a correlation matrix?
> 
> Yes, so I think each correlation-pair should become a column. But with `affect_columns` it is possible to operate on a subset.
> 
> > The only issue right now is that tf_crosscor() requires the same domain for x and y, i.e. we would have to transform it to the same domain first, I guess we would have to truncate it to the smallest domain.
> 
> Good point. The `tf_crosscor` has an argument `arg`, maybe we just let the user set this optionally?

The grid of x and y need to be identical, so I think the user should just provide the grid, because there would be way to many ways of reshaping the grid otherwise. Here is a draft https://github.com/mlr-org/mlr3fda/blob/feat/corr/R/PipeOpFDACor.R#L54 of what I would propose, would then need to check how we want to handle the error when the provided grid is not identical, etc.

**Comment by sebffischer** [comment]
The prototype makes sense! :)

> would then need to check how we want to handle the error when the provided grid is not identical, 

I don't fully understand what you mean, we just allow to pass one grid, so it is always identical, no?

**Comment by m-muecke** [comment]
> The prototype makes sense! :)
> 
> > would then need to check how we want to handle the error when the provided grid is not identical,
> 
> I don't fully understand what you mean, we just allow to pass one grid, so it is always identical, no?

I thought the grid points have to be identical between the x and y, but it's only required that the vectors have same length and the same domain, but the actual grid may differ. I've adjusted the prototype to accommodate regular data already.

**Comment by sebffischer** [comment]
Required in code or required mathematically?

**Comment by m-muecke** [comment]
> Required in code or required mathematically?

Required in the code, but mathematically I believe as well otherwise calculating the covariance will be challenging.

**Comment by fabian-s** [comment]
> > The prototype makes sense! :)
> > > would then need to check how we want to handle the error when the provided grid is not identical,
> > 
> > 
> > I don't fully understand what you mean, we just allow to pass one grid, so it is always identical, no?
> 
> I thought the grid points have to be identical between the x and y, but it's only required that the vectors have same length and the same domain, but the actual grid may differ. I've adjusted the prototype to accommodate regular data.

not sure if this is beside the point here but:

- in terms of implementation, `tf_crosscov` always interpolates both function vectors onto the same grid given by its `arg`-argument, defaulting to the grid of the first function vector 
(https://github.com/tidyfun/tf/blob/7e11b00573024f904911ce31c0b98e5442242796/R/fwise.R#L139-L140)
- mathematically, if the two stochastic processes x(t), y(s) you want to correlate do not have a shared domain, the cross-covariance is not (well-)defined, I think. for that, you'd also need to define a 1-to-1 mapping between their domains T and S to know which function value x(t),  t in T, to correlate with which function value y(s), s in S.  
(A sensible default for that might be to linearly scale both T and S to [0, 1] and use that.)

**Comment by m-muecke** [comment]
@fabian-s 

Cheers for the input, scaling to [0, 1] seems to make more sense then what I did scaling x and y to the maximum lower bound and minimum upper bound. With regards to the interpolation I think thats fine, since the user can always provide a different grid with `arg` argument.

**Comment by sebffischer** [comment]
I think in mlr3 we should not re-scale the functions by default. What if we have two functions where the `x` axis is the time, but they are measured in disjunct intervals? If we want this re-scaling I think it should be opt-in.

**Comment by fabian-s** [comment]
> @fabian-s
> 
> Cheers for the input, scaling to [0, 1] seems to make more sense then what I did scaling x and y to the maximum lower bound and minimum upper bound of x and y. With regards to the interpolation I think thats fine, since the user can always provide a different grid with `arg` argument.
> 
> Ah but the scaling to [0, 1] doesn't work when its outside the domain see the following example:
> 
> ```r
> library(tf, quietly = TRUE)
> 
> scale_min_max = function(x) {
>   lower = min(x, na.rm = TRUE)
>   upper = max(x, na.rm = TRUE)
>   (x - lower) / (upper - lower)
> }
> 
> x = tf_rgp(100L, arg = 1:100)
> arg = tf_arg(x)
> new_arg = scale_min_max(x)
> x = tfd(x, arg = new_arg)
> #> Error in `map()`:
> #> ℹ In index: 1.
> #> ℹ With name: 1.
> #> Caused by error in `.assert_arg_vector()`:
> #> ! Assertion on 'arg' failed: Element 1 is not >= 1.
> ```
> 
> Created on 2024-06-19 with [reprex v2.1.0](https://reprex.tidyverse.org)

 you need:
 
 ```r
library(tf, quietly = TRUE)

scale_min_max = function(x) {
  lower = min(x, na.rm = TRUE)
  upper = max(x, na.rm = TRUE)
  (x - lower) / (upper - lower)
}

x = tf_rgp(100L, arg = 1:100)
arg = tf_arg(x)
new_arg = scale_min_max(arg)
x_01 = tfd(tf_evaluations(x), arg = new_arg)
```
- `new_arg` needs to be the rescaled `arg`, not `x`4
- can't assign arg-values outside the domain of your `tf`-input in `tfd.tf`. you need to provide the list of function values `tf_evaluations(x)` along  with the new grid (this calls `tfd.list`)

**Comment by m-muecke** [comment]
Ah okey, the first was a typo, the second explains the error.
